### ISSUE TITLE
race condition with /dev/fd/* files

### ISSUE THREAD

**Issue by symphorien** [orivej/fptrace#1]
Steps to reproduce:

```
$ fptrace -d deps.json nix-shell '<nixpkgs>' -A htop --run "genericBuild"
[...]
shrinking RPATHs of ELF executables and libraries in /nix/store/fjwsikvhzm5lxwrk6nv0kwp0msbvzd68-htop-2.0.2
main.sysexit (main.go:315): stat /dev/fd/63: no such file or directory
```

here, fptrace from commit  14594cc and nixpkgs 17.09beta627.11c88047b8

Most unfortunately, fptrace exits without saving an (incomplete) `deps.json` to disk.

**Comment by orivej** [comment]
Luckily this is not a race: the issue is that `/dev/fd` is process-relative, and `/dev/fd/63` of a child process is not the same as `/dev/fd/63` of the monitoring process. I'll fix this.

**Comment by symphorien** [comment]
thanks !
